version: '3.8'
services:
  migration-service:
    build: .
    ports:
      - "8083:8083"
    depends_on:
      - db
    networks:
      - my-network

  db:
    image: postgres:15-alpine
    container_name: postgres_container_migration
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - my-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  my-network:
    driver: bridge

volumes:
  postgres_data:
