spring:
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: 123123
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
logging:
  level:
    liquibase: DEBUG
